name: Publish siggler to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/siggler
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up package manager
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Build distribution packages
        run: uv build --no-sources

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1